from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib import colors
import json, os
import matplotlib.pyplot as plt


def generate_alignment_chart(mapping_results, outfile="results/alignment_chart.png"):
    if not mapping_results:
        # Create empty chart
        plt.figure(figsize=(6, 4))
        plt.bar(["No Data"], [0], color=["#808080"])
        plt.title("Alignment Data")
        plt.savefig(outfile, bbox_inches="tight")
        plt.close()
        return outfile
    
    counts = {"Fully aligned": 0, "Partial match": 0, "Missing": 0}
    for r in mapping_results:
        status = r.get("status")
        if status in counts:
            counts[status] += 1
    
    plt.figure(figsize=(6, 4))
    plt.bar(counts.keys(), counts.values(), color=["#4CAF50", "#FFC107", "#F44336"])
    plt.title("Curriculum Alignment Overview")
    plt.savefig(outfile, bbox_inches="tight")
    plt.close()
    return outfile

def create_report(json_file, output="results/final_report.pdf"):
    with open(json_file, "r", encoding='utf-8') as f:
        data = json.load(f)

    doc = SimpleDocTemplate(
        output,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=60,
        bottomMargin=50
    )

    # ---------- Improved Spacing and Readability Styles ----------
    styles = getSampleStyleSheet()

    title = ParagraphStyle(
        "Title",
        fontSize=24,
        spaceAfter=30,
        alignment=1,
        textColor=colors.HexColor("#1A3E72")
    )

    header = ParagraphStyle(
        "Header",
        fontSize=17,
        spaceBefore=20,
        spaceAfter=18,
        leading=22,
        textColor=colors.HexColor("#0A5275")
    )

    subheader = ParagraphStyle(
        "Subheader",
        fontSize=14,
        spaceBefore=15,
        spaceAfter=10,
        leading=20,
        textColor=colors.darkred
    )

    body = ParagraphStyle(
        "Body",
        fontSize=11.5,
        leading=20,
        spaceAfter=10,
    )

    bullet = ParagraphStyle(
        "Bullet",
        fontSize=11.5,
        leading=20,
        leftIndent=25,
        bulletIndent=15,
        spaceAfter=8,
    )

    small_body = ParagraphStyle(
        "SmallBody",
        fontSize=10.5,
        leading=18,
        spaceAfter=8,
    )

    elements = []

    # -------- Cover Page --------
    elements.append(Paragraph("📘 Curriculum Gap Analysis Report", title))
    elements.append(Spacer(1, 25))
    elements.append(Paragraph("<b>Generated by:</b> AI Curriculum Mapping System", body))
    elements.append(Paragraph("<b>Use Case:</b> Curriculum–Standards Alignment Evaluation", body))
    elements.append(Paragraph("<b>Version:</b> 1.0", body))
    elements.append(Spacer(1, 200))
    elements.append(Paragraph("📍 CONFIDENTIAL DOCUMENT — NOT FOR PUBLIC DISTRIBUTION", subheader))
    elements.append(PageBreak())

    # -------- Coverage Summary --------
    elements.append(Paragraph("📍 Coverage Summary", header))
    elements.append(Spacer(1, 10))
    mapping_data = data.get("mapping_results", data.get("gaps", []))
    
    if mapping_data:
        # Summary stats
        total = len(mapping_data)
        aligned = sum(1 for m in mapping_data if m.get("status") == "Fully aligned")
        partial = sum(1 for m in mapping_data if m.get("status") == "Partial match")
        missing = sum(1 for m in mapping_data if m.get("status") == "Missing")
        
        elements.append(Paragraph(f"<b>Total Topics:</b> {total}", body))
        elements.append(Paragraph(f"<b>Fully Aligned:</b> {aligned} ({aligned/total*100:.1f}%)", body))
        elements.append(Paragraph(f"<b>Partial Matches:</b> {partial} ({partial/total*100:.1f}%)", body))
        elements.append(Paragraph(f"<b>Missing:</b> {missing} ({missing/total*100:.1f}%)", body))
        elements.append(Spacer(1, 15))
        
        # Sample of mapping
        elements.append(Paragraph("<b>Sample Mapping:</b>", subheader))
        for i, item in enumerate(mapping_data[:5]):  # Show first 5
            text = f"{item.get('standard_topic', 'Unknown')} → {item.get('closest_curriculum_topic', 'None')} ({item.get('status', 'Unknown')})"
            elements.append(Paragraph(text, small_body))
        
        if len(mapping_data) > 5:
            elements.append(Paragraph(f"... and {len(mapping_data) - 5} more topics", small_body))
    else:
        elements.append(Paragraph("No mapping data available.", body))

    elements.append(Spacer(1, 20))

    # -------- Alignment Chart --------
    chart = generate_alignment_chart(mapping_data)
    elements.append(Image(chart, width=5.5 * inch, height=3 * inch))
    elements.append(Spacer(1, 30))

    # -------- Missing Topics --------
    elements.append(Paragraph("❗ Critical Gaps Requiring Attention", header))
    elements.append(Spacer(1, 10))

    missing = [m for m in mapping_data if m.get("status") == "Missing"]
    partial = [m for m in mapping_data if m.get("status") == "Partial match"]

    if missing:
        elements.append(Paragraph("<b>Missing Topics:</b>", subheader))
        for m in missing:
            similarity = m.get('similarity', 0)
            elements.append(Paragraph(f"⚠ {m.get('standard_topic', 'Unknown topic')} (Similarity: {similarity:.2f})", bullet))
    
    if partial:
        elements.append(Spacer(1, 10))
        elements.append(Paragraph("<b>Partial Matches (Need Enhancement):</b>", subheader))
        for p in partial:
            similarity = p.get('similarity', 0)
            elements.append(Paragraph(f"⚡ {p.get('standard_topic', 'Unknown topic')} (Similarity: {similarity:.2f})", bullet))

    if not missing and not partial:
        elements.append(Paragraph("✔ No significant gaps detected.", body))

    elements.append(PageBreak())

    # -------- DETAILED RECOMMENDATIONS --------
    elements.append(Paragraph("🧠 Detailed Analysis & Recommendations", header))
    elements.append(Spacer(1, 10))

    recommendations = data.get("recommendations", "")
    
    if recommendations and isinstance(recommendations, str):
        # Process the detailed structured recommendations
        lines = recommendations.split('\n')
        current_section = ""
        
        for line in lines:
            line = line.strip()
            if not line:
                elements.append(Spacer(1, 5))
                continue
                
            # Handle section headers (### or **)
            if line.startswith('### '):
                current_section = line[4:].strip()
                elements.append(Paragraph(f"<b>{current_section}</b>", subheader))
                elements.append(Spacer(1, 8))
            elif line.startswith('**') and line.endswith('**'):
                current_section = line[2:-2].strip()
                elements.append(Paragraph(f"<b>{current_section}</b>", subheader))
                elements.append(Spacer(1, 8))
            # Handle numbered lists (1., 2., etc.)
            elif line[0].isdigit() and len(line) > 1 and line[1] == '.':
                elements.append(Paragraph(line, bullet))
            # Handle bullet points (- or *)
            elif line.startswith('- ') or line.startswith('* '):
                elements.append(Paragraph(f"• {line[2:]}", bullet))
            # Handle sub-bullets with indentation
            elif line.startswith('  * ') or line.startswith('  - '):
                elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;• {line[4:]}", bullet))
            # Handle Bloom's taxonomy items
            elif '* ' in line and ':' in line:
                elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;• {line}", bullet))
            # Bold text within paragraphs
            elif '**' in line:
                # Replace **text** with <b>text</b>
                import re
                formatted_line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
                elements.append(Paragraph(formatted_line, body))
            # Regular paragraph
            elif len(line) > 1:
                elements.append(Paragraph(line, body))
    else:
        elements.append(Paragraph("Detailed analysis completed. Review sections below.", body))
        elements.append(Spacer(1, 15))
        
        # Fallback: Show summary from data
        elements.append(Paragraph("<b>Key Findings:</b>", subheader))
        summary = data.get("summary", {})
        if summary:
            elements.append(Paragraph(f"Coverage Score: {summary.get('coverage', 'N/A')}", body))
            elements.append(Paragraph(f"Topics Covered: {summary.get('topicsCovered', 0)} / {summary.get('totalTopics', 0)}", body))
            elements.append(Paragraph(f"Gaps Identified: {summary.get('gaps', 0)}", body))
            elements.append(Paragraph(f"Recommendations: {summary.get('recommendations', 0)}", body))

    elements.append(PageBreak())

    # -------- Next Steps & Roadmap --------
    elements.append(Paragraph("🧭 Implementation Roadmap & Next Steps", header))
    elements.append(Spacer(1, 10))
    
    elements.append(Paragraph("<b>Immediate Actions (Week 1-2):</b>", subheader))
    immediate_actions = [
        "Review and prioritize high-severity gaps",
        "Assign responsibility for each gap to team members",
        "Create initial action plan for top 3 gaps",
        "Schedule stakeholder review meeting"
    ]
    for action in immediate_actions:
        elements.append(Paragraph(f"• {action}", bullet))
    
    elements.append(Spacer(1, 15))
    elements.append(Paragraph("<b>Short-term Actions (Month 1-3):</b>", subheader))
    short_term = [
        "Develop new learning materials for missing topics",
        "Update existing curriculum modules",
        "Train instructors on new content",
        "Implement assessment changes"
    ]
    for action in short_term:
        elements.append(Paragraph(f"• {action}", bullet))
    
    elements.append(Spacer(1, 15))
    elements.append(Paragraph("<b>Medium-term Actions (Month 3-6):</b>", subheader))
    medium_term = [
        "Complete curriculum redesign",
        "Pilot new curriculum with test group",
        "Collect and analyze feedback",
        "Refine based on pilot results"
    ]
    for action in medium_term:
        elements.append(Paragraph(f"• {action}", bullet))
    
    elements.append(Spacer(1, 15))
    elements.append(Paragraph("<b>Long-term Actions (Month 6-12):</b>", subheader))
    long_term = [
        "Full implementation across all courses",
        "Establish continuous improvement process",
        "Set up regular review cycles",
        "Integrate with learning management system"
    ]
    for action in long_term:
        elements.append(Paragraph(f"• {action}", bullet))

    doc.build(elements)
    return output